# Generated by Django 4.2.6 on 2023-11-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('slug', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The movie title', max_length=200)),
                ('overview', models.CharField(blank=True, help_text='Overview', max_length=200)),
                ('language', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('vote_average', models.FloatField(default=0.0, help_text='Movie rating')),
                ('popularity', models.FloatField(blank=True, default=0.0)),
                ('release_date', models.DateField()),
                ('poster_path', models.ImageField(blank=True, upload_to='posters')),
                ('backdrop_path', models.ImageField(blank=True, upload_to='backdrops')),
                ('genres', models.ManyToManyField(to='tmdb_database.genre')),
            ],
        ),
    ]
