# Generated by Django 4.2.6 on 2023-11-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb_database', '0002_menuitem_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The movie title', max_length=200)),
                ('vote_average', models.FloatField(default=0.0, help_text='Movie rating')),
                ('release_date', models.DateField()),
                ('poster_path', models.ImageField(upload_to='posters')),
            ],
        ),
    ]
