# Generated by Django 4.2.6 on 2023-11-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb_database', '0003_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='original_title',
        ),
    ]
