# Generated by Django 4.2.6 on 2023-11-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb_database', '0004_rename_title_movie_original_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='original_title',
            new_name='title',
        ),
    ]
