# Generated by Django 4.2.6 on 2023-11-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb_database', '0005_rename_original_title_movie_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
