# Generated by Django 4.2.6 on 2023-11-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb_database', '0006_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='tmdb_database.genre'),
        ),
    ]
