# Generated by Django 4.2.6 on 2023-11-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb_database', '0007_movie_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-vote_average']},
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(default=0.0),
        ),
    ]
