# Generated by Django 4.2.6 on 2023-11-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb_database', '0008_alter_movie_options_movie_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
